/**
 * This file was generated by the Jeddict
 */
package ch.zhaw.gpi.gwr.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author scep
 */
@Entity(name="Wohnung")
public class DwellingEntity implements Serializable {

    @Column(unique = true, nullable = false)
    @Id
    @NotNull
    @Size(min = 12, max = 12)
    private String WHGNR;

    @Column(nullable = false)
    @Basic(optional = false)
    @NotNull
    @Min(value = 3100)
    @Max(value = 3419)
    private int WSTWK;

    @Column(nullable = false)
    @Basic(optional = false)
    @NotNull
    @Min(value = 1)
    @Max(value = 2)
    private int WMEHRG;

    @Column(nullable = false)
    @Basic(optional = false)
    @NotNull
    @Size(min = 3, max = 40)
    private String WBEZ;

    @Column(nullable = false)
    @Basic(optional = false)
    @NotNull
    @Min(value = 1)
    @Max(value = 99)
    private int WAZIM;

    @ManyToOne(targetEntity = BuildingEntity.class)
    @JoinColumn(name = "GEBID")
    private BuildingEntity Gebaeude;

    public String getWHGNR() {
        return this.WHGNR;
    }

    public void setWHGNR(String WHGNR) {
        this.WHGNR = WHGNR;
    }

    public int getWSTWK() {
        return this.WSTWK;
    }

    public void setWSTWK(int WSTWK) {
        this.WSTWK = WSTWK;
    }

    public int getWMEHRG() {
        return this.WMEHRG;
    }

    public void setWMEHRG(int WMEHRG) {
        this.WMEHRG = WMEHRG;
    }

    public String getWBEZ() {
        return this.WBEZ;
    }

    public void setWBEZ(String WBEZ) {
        this.WBEZ = WBEZ;
    }

    public int getWAZIM() {
        return this.WAZIM;
    }

    public void setWAZIM(int WAZIM) {
        this.WAZIM = WAZIM;
    }

    public BuildingEntity getGebaeude() {
        return this.Gebaeude;
    }

    public void setGebaeude(BuildingEntity Gebaeude) {
        this.Gebaeude = Gebaeude;
    }

}